### ISSUE TITLE
API Server v1.0.0-beta roadmap

### ISSUE THREAD

**Issue by kamekyame** [codeforkosen/Kakomimasu#161]
- [x] ログイン機能の実装
- [x] アカウント登録時のパスワード入力をなくす(#183,#184)
- [x] ゲーム参加、アクション送信にaccessTokenを指定しないといけないようにする(‘Authorization‘ヘッダーを使って)(#183,#184)
- [x] deps.tsを作る(#178)
- [x] 今はnullになっているGame.players内のtilePoint,areaPointを削除(points.tilePoint,points.areaPointを使用) (#179)
- [x] apiserver/api_client.js,.d.tsをclient_jsに移動(#182)
- [x] ~~jwtライブラリをfirebase-adminに変更する~~
- [x] deno lint警告を出来る限り解消(#185)
- [x] restore関数のテストを追加(#189)
- [x] deno fmtのテストをGithubActionsに追加(#191)
- [x] Github ActionsのDockerで行っているdeno testをDockerを使わないように変更(#192)

**Comment by kamekyame** [comment]
jwtライブラリをfirebacse-adminに変更する
という項目ですが、秘密鍵をサーバに取り込む必要があり、githubで公開することができないため、現状のまま行こうと思います。

**Comment by ninja03** [comment]
良いと思います！
